# Generated by Django 5.2.6 on 2025-10-08 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actor_photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Актёр',
                'verbose_name_plural': 'Актёры',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='Actor',
            field=models.ManyToManyField(related_name='movies', to='movies.actor', verbose_name='Актёр'),
        ),
    ]
